# Generated by Django 6.0 on 2026-08-06 11:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='Scaife Tech Lapping & Coating', max_length=100)),
                ('tagline', models.CharField(default='Precision Engineering for Diamond Scaifes', max_length=200)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='branding/')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='branding/')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='branding/')),
                ('contact_email', models.EmailField(default='contact@scaifetech.com', max_length=254)),
                ('contact_phone', models.CharField(default='+91 98765 43210', max_length=20)),
                ('address', models.TextField(default='123 Diamond Industrial Estate, Surat, Gujarat, India')),
                ('office_hours', models.CharField(default='Mon - Sat: 9:00 AM - 6:00 PM', max_length=100)),
                ('whatsapp_number', models.CharField(default='+91 98765 43210', max_length=20)),
                ('google_map_embed', models.TextField(blank=True, default='https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3719.8276023737227!2d72.86311681493527!3d21.199014185908866!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3be04f21db5ab1c1%3A0x7d6a505e94b29bb8!2sVarachha%20Road%2C%20Surat%2C%20Gujarat%2C%20India!5e0!3m2!1sen!2sus!4v1620000000000!5m2!1sen!2sus', null=True)),
                ('footer_text', models.TextField(default='© 2026 Scaife Tech. All rights reserved. Premium lapping & coating solutions.')),
                ('facebook_url', models.URLField(blank=True, default='https://facebook.com')),
                ('twitter_url', models.URLField(blank=True, default='https://twitter.com')),
                ('linkedin_url', models.URLField(blank=True, default='https://linkedin.com')),
                ('instagram_url', models.URLField(blank=True, default='https://instagram.com')),
                ('smtp_host', models.CharField(blank=True, default='smtp.gmail.com', max_length=100)),
                ('smtp_port', models.IntegerField(default=587)),
                ('smtp_user', models.CharField(blank=True, max_length=100)),
                ('smtp_password', models.CharField(blank=True, max_length=100)),
                ('smtp_use_tls', models.BooleanField(default=True)),
                ('smtp_use_ssl', models.BooleanField(default=False)),
                ('smtp_from_email', models.EmailField(blank=True, default='noreply@scaifetech.com', max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField()),
                ('display_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='GalleryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='gallery/')),
                ('category', models.CharField(choices=[('office', 'Office & Infrastructure'), ('machine', 'Lapping & Coating Machinery'), ('process', 'Work Process'), ('product', 'Finished Scaifes')], default='process', max_length=20)),
                ('display_order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('resolved', 'Resolved')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='PricingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lapping_standard', models.DecimalField(decimal_places=2, default=150.0, max_digits=10)),
                ('lapping_precision', models.DecimalField(decimal_places=2, default=250.0, max_digits=10)),
                ('lapping_ultra', models.DecimalField(decimal_places=2, default=400.0, max_digits=10)),
                ('coating_standard', models.DecimalField(decimal_places=2, default=200.0, max_digits=10)),
                ('coating_premium', models.DecimalField(decimal_places=2, default=350.0, max_digits=10)),
                ('coating_dlc', models.DecimalField(decimal_places=2, default=600.0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='team/')),
                ('bio', models.TextField(blank=True)),
                ('display_order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100)),
                ('company', models.CharField(blank=True, max_length=100)),
                ('review_text', models.TextField()),
                ('rating', models.IntegerField(default=5)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(max_length=50)),
                ('model_name', models.CharField(blank=True, max_length=100)),
                ('object_repr', models.CharField(blank=True, max_length=200)),
                ('details', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ScaifeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100)),
                ('serial_number', models.CharField(max_length=50, unique=True)),
                ('diameter', models.DecimalField(decimal_places=2, help_text='Diameter in inches', max_digits=5)),
                ('lapping_type', models.CharField(choices=[('none', 'No Lapping'), ('standard', 'Standard Lapping'), ('precision', 'Precision Lapping'), ('ultra', 'Ultra-Precision Lapping')], default='standard', max_length=20)),
                ('coating_type', models.CharField(choices=[('none', 'No Coating'), ('standard', 'Standard Coating'), ('premium', 'Premium Coating'), ('dlc', 'Diamond-Like Carbon (DLC)')], default='standard', max_length=20)),
                ('status', models.CharField(choices=[('received', 'Received'), ('lapping', 'In Lapping'), ('coating', 'In Coating'), ('qc', 'Quality Control'), ('ready', 'Ready for Delivery'), ('delivered', 'Delivered')], default='received', max_length=20)),
                ('cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('received_date', models.DateField(auto_now_add=True)),
                ('target_date', models.DateField(blank=True, null=True)),
                ('return_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('assigned_office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scaife_entries', to='core.office')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_entries', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Super Admin'), ('manager', 'Office Manager'), ('worker', 'Office Worker')], default='worker', max_length=20)),
                ('office', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff', to='core.office')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
