# Generated by Django 6.0 on 2026-08-06 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricingconfig',
            name='coating_dlc',
        ),
        migrations.RemoveField(
            model_name='pricingconfig',
            name='coating_premium',
        ),
        migrations.RemoveField(
            model_name='pricingconfig',
            name='coating_standard',
        ),
        migrations.RemoveField(
            model_name='pricingconfig',
            name='lapping_precision',
        ),
        migrations.RemoveField(
            model_name='pricingconfig',
            name='lapping_standard',
        ),
        migrations.RemoveField(
            model_name='pricingconfig',
            name='lapping_ultra',
        ),
        migrations.AddField(
            model_name='pricingconfig',
            name='coating_rate',
            field=models.DecimalField(decimal_places=2, default=200.0, help_text='Coating rate per inch (INR)', max_digits=10),
        ),
        migrations.AddField(
            model_name='pricingconfig',
            name='lapping_rate',
            field=models.DecimalField(decimal_places=2, default=150.0, help_text='Lapping rate per inch (INR)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='scaifeentry',
            name='coating_type',
            field=models.CharField(choices=[('yes', 'Coating'), ('no', 'No Coating')], default='yes', max_length=20),
        ),
        migrations.AlterField(
            model_name='scaifeentry',
            name='lapping_type',
            field=models.CharField(choices=[('yes', 'Lapping'), ('no', 'No Lapping')], default='yes', max_length=20),
        ),
    ]
