# Generated by Django 6.0 on 2026-08-06 13:10

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_pricingconfig_coating_dlc_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('base_salary', models.DecimalField(decimal_places=2, default=0.0, help_text='Base monthly/per-term salary in INR', max_digits=10)),
                ('joining_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('office', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workers', to='core.office')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='worker_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WorkerFinancialEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('salary', '💰 Salary (પગાર)'), ('advance', '💵 Advance (એડવાન્સ)'), ('cash_taken', '🏦 Cash Taken (ઉપાડ)'), ('leave', '📅 Leave (રજા)'), ('bonus', '🎁 Bonus (બોનસ)'), ('deduction', '➖ Deduction (કપાત)'), ('expense', '💸 Expense (ખર્ચ)'), ('income', '📈 Income (આવક)'), ('payment', '💳 Payment (ચુકવણી)')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('leave_days', models.IntegerField(default=0, help_text='Number of leave days (for Leave entry type)')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_entries', to='core.workerprofile')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
