# Generated by Django 6.0 on 2026-08-06 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_workerprofile_workerfinancialentry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workerprofile',
            name='office',
        ),
        migrations.RemoveField(
            model_name='workerprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='WorkerFinancialEntry',
        ),
        migrations.DeleteModel(
            name='WorkerProfile',
        ),
    ]
