# Generated by Django 6.0 on 2026-08-07 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_readd_worker_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='office',
            name='manager_username',
            field=models.CharField(blank=True, default='', help_text='Auto-generated manager login username', max_length=150),
        ),
    ]
