# Generated by Django 6.0 on 2026-08-07 07:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_office_manager_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scaifeentry',
            name='coating_type',
        ),
        migrations.RemoveField(
            model_name='scaifeentry',
            name='lapping_type',
        ),
        migrations.AddField(
            model_name='pricingconfig',
            name='diamond_scaife_rate',
            field=models.DecimalField(decimal_places=2, default=300.0, help_text='Diamond Scaife rate per scaife (INR)', max_digits=10),
        ),
        migrations.AddField(
            model_name='scaifeentry',
            name='quantity',
            field=models.IntegerField(default=1, help_text='Quantity of Scaifes'),
        ),
        migrations.AddField(
            model_name='scaifeentry',
            name='service_coating',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='scaifeentry',
            name='service_diamond_scaife',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='scaifeentry',
            name='service_lapping',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='pricingconfig',
            name='coating_rate',
            field=models.DecimalField(decimal_places=2, default=200.0, help_text='Coating rate per scaife (INR)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='pricingconfig',
            name='lapping_rate',
            field=models.DecimalField(decimal_places=2, default=150.0, help_text='Lapping rate per scaife (INR)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='scaifeentry',
            name='assigned_office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scaife_entries', to='core.office'),
        ),
        migrations.AlterField(
            model_name='scaifeentry',
            name='diameter',
            field=models.DecimalField(decimal_places=2, default=1.0, help_text='Plate Diameter in inches (legacy)', max_digits=5),
        ),
        migrations.AlterField(
            model_name='scaifeentry',
            name='serial_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
