# Generated by Django 6.0 on 2026-08-07 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_add_office_credential_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='scaifeentry',
            name='quantity_coating',
            field=models.IntegerField(default=0, help_text='Quantity of Coating Scaifes'),
        ),
        migrations.AddField(
            model_name='scaifeentry',
            name='quantity_diamond',
            field=models.IntegerField(default=0, help_text='Quantity of Diamond Scaifes'),
        ),
        migrations.AddField(
            model_name='scaifeentry',
            name='quantity_lapping',
            field=models.IntegerField(default=0, help_text='Quantity of Lapping Scaifes'),
        ),
    ]
