# Generated by Django 6.0 on 2026-08-07 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_add_service_quantity_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandingsettings',
            name='admin_security_pin',
            field=models.CharField(default='1234', help_text='Master Security PIN required to reveal office manager passwords', max_length=20),
        ),
    ]
