# Generated by Django 6.0 on 2026-08-10 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_add_repair_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandingsettings',
            name='admin_whatsapp',
            field=models.CharField(blank=True, default='', help_text="Admin's WhatsApp number for receiving notifications (with country code, e.g. 919876543210)", max_length=20),
        ),
        migrations.AddField(
            model_name='office',
            name='manager_whatsapp',
            field=models.CharField(blank=True, default='', help_text="Manager's WhatsApp number (with country code, e.g. 919876543210)", max_length=20),
        ),
    ]
