# Generated by Django 6.0 on 2026-08-13 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_add_whatsapp_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brandingsettings',
            name='admin_whatsapp',
        ),
        migrations.RemoveField(
            model_name='brandingsettings',
            name='smtp_from_email',
        ),
        migrations.RemoveField(
            model_name='brandingsettings',
            name='smtp_host',
        ),
        migrations.RemoveField(
            model_name='brandingsettings',
            name='smtp_password',
        ),
        migrations.RemoveField(
            model_name='brandingsettings',
            name='smtp_port',
        ),
        migrations.RemoveField(
            model_name='brandingsettings',
            name='smtp_use_ssl',
        ),
        migrations.RemoveField(
            model_name='brandingsettings',
            name='smtp_use_tls',
        ),
        migrations.RemoveField(
            model_name='brandingsettings',
            name='smtp_user',
        ),
    ]
